### ISSUE TITLE
Line 61 of dockerfile

### ISSUE THREAD

**Issue by keyoun** [tatsuo-ishii/docker-pgpool-II-pgpool_setup#3]
Line 61: RUN sed -ri 's/Groupr apache/Group postgres/' /etc/httpd/conf/httpd.conf
Looks like an extra "r" after Group, this should be:
Line 61: RUN sed -ri 's/Group apache/Group postgres/' /etc/httpd/conf/httpd.conf

**Comment by tatsuo-ishii** [comment]
Fixed. Thanks!
